### ISSUE TITLE
如果你在杭州，要不要来我们公司试试 😄

### ISSUE THREAD

**Issue by caoxiemeihao** [Owen-Tsai/salmon-ui#14]

**Comment by Owen-Tsai** [comment]
由于家人身体的问题所以近期只能考虑 remote 和济南本地的机会。PITY！情况有所好转时我会考虑，谢谢。

Keep building epic shit! ✌️

**Comment by caoxiemeihao** [comment]
或者你可以考虑试试国外的远程工作，你这么秀的英语 :)
https://mui.com/zh/careers/react-engineer
